#!/usr/bin/env bash
if [[ -z $NAME ]]; then
  echo Please set the NAME varaible to the name of the service without f8-
  exit 1
fi

DEB_DIR=deb_$NAME
ARCH=$(dpkg --print-architecture)

mkdebdir() {
  if [ ! -d $DEB_DIR$1 ]; then
    mkdir -p $DEB_DIR$1
  fi
}

if [[ ! -d $DEB_DIR ]]; then
  echo Please create $DEB_DIR directory first with DEBIAN inside it >&2
  exit 1
fi

if [[ ! -d $DEB_DIR/DEBIAN ]]; then
  echo Please create DEBIAN directory in $DEB_DIR with control file >&2
  exit 1
fi

VERSION=unknown

if [[ $CI_BRANCH =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
  VERSION=${VERSION:1}
elif [[ $CI_BRANCH =~ ^release/([0-9]+.[0-9]+){1}$ ]]; then
  VERSION="${BASH_REMATCH[1]}RC-${CI_COMMIT_ID}"
else
  VERSION="0.0.0-${CI_COMMIT_ID}-${CI_BRANCH}"
fi

VERSION=$(sed "s/\//-/g" <<< $VERSION)

sed -i.bak "s/CI_VERSION/$VERSION/g" $DEB_DIR/DEBIAN/control

# Include packaging instructions
source package.sh

dpkg-deb --build $DEB_DIR

NEW_DEB=f8-${NAME}_${VERSION}_${ARCH}.deb
if [[ ! -e $DEB_DIR.deb ]]; then
  echo Failed to build $DEB_DIR >&2
  exit 1
fi
mv $DEB_DIR.deb $NEW_DEB
echo Produced $NEW_DEB

sed -i.bak "s/$VERSION/CI_VERSION/g" $DEB_DIR/DEBIAN/control
