#!/usr/bin/env bash

set -e

runner() {
  pip install --user semver
  curl https://raw.githubusercontent.com/ConnectedVentures/f8-deb-helper/feature/latest-helper/latest-helper > latest-helper
  chmod +x latest-helper
  latest_version=$(./latest-helper $VERSION)

  wget -qO- "https://github.com/ConnectedVentures/f8-deb-helper/archive/${latest_version}.tar.gz" | tar xvz

  rm -rf f8-deb-helper
  mv f8-deb-helper-$(tr -d 'v' <<< $latest_version) f8-deb-helper

  for file in deb_*; do
    export NAME="${file/deb_/}"
    ./f8-deb-helper/build-deb
    ./f8-deb-helper/push-deb
  done
}

runner
