#!/usr/bin/env bash
ENV=testing
if [[ $CI_BRANCH =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
  ENV=production
elif [[ $CI_BRANCH =~ ^release/[0-9]+.[0-9]+$ ]]; then
  ENV=staging
else
  ENV=testing
fi

APT_REPO="${APT_REPO:-public.apt.fresh8.co}"
ARCH=$(dpkg --print-architecture)

CI_USER="${CI_USER:-codeship}"

LATEST=$(ls -t1 f8-$NAME*.deb 2>/dev/null | head -n 1)

if [[ -z $LATEST ]]; then
  echo No .deb files found for $NAME >&2
  exit 1
fi

REPO_PATH=/dists/fresh8/$ENV/binary-$ARCH/$LATEST
echo "scp $LATEST $CI_USER@$APT_REPO:$REPO_PATH"
scp $LATEST $CI_USER@$APT_REPO:$REPO_PATH

echo "ssh $CI_USER@$APT_REPO 'chmod 0775 '$REPO_PATH'; ENV='$ENV' apt-rescan'"
ssh $CI_USER@$APT_REPO 'chmod 0775 '$REPO_PATH'; ENV='$ENV' apt-rescan'
