#!/usr/bin/env bash
APT_REPO="${APT_REPO:-public.apt.fresh8.co}"
ARCH=$(dpkg --print-architecture)

CI_USER="${CI_USER:-codeship}"

LATEST=$(ls -t1 f8-$NAME*.deb 2>/dev/null | head -n 1)

if [[ -z $LATEST ]]; then
  echo No .deb files found for $NAME >&2
  exit 1
fi

REPO_PATH=/dists/fresh8/production/binary-$ARCH/$LATEST
scp $LATEST $CI_USER@$APT_REPO:$REPO_PATH

ssh $CI_USER@$APT_REPO 'chmod 0775 '$REPO_PATH'; apt-rescan'
